spring:
  boot:
    admin:
      client:
        url: http://localhost:1010

management:
  endpoints:
    web:
      exposure:
        include: '*'

app:
  message:
    ssnwebapi: "http://13.233.152.39:1234/citizen-details"
    successmessage:  "Citizen is Successfully Register"
    failedmessage:  "Citizen Not Belong to Rhode Island, Application Registration Failed"
 
