spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HIS
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: java
  jpa:
    hibernate: 
      ddl-auto: update
    show-sql: true   
    properties:
       hibernate:
        dialect: org.hibernate.dialect.MySQLDialect    
  
  boot:
    admin:
      client:
        url: http://localhost:1010

management:
  endpoints:
    web:
      exposure:
        include: '*'

app:
  messages:
    ssnwebapi: "http://13.233.152.39:1234/citizen-details"
    successmessage:  "Citizen is Successfully Register"
    failedmessage:  "Citizen Not Belong to Rhode Island, Application Registration Failed"
 
