spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HIS
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: java
  jpa:
    hibernate: 
      ddl-auto: update
    show-sql: true   
    properties:
       hibernate:
        dialect: org.hibernate.dialect.MySQLDialect    
  
  boot:
    admin:
      client:
        url: http://localhost:1010
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: yeshu96183@gmail.com
    password: ivry cvdt injy sqeh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        
management:
  endpoints:
    web:
      exposure:
        include: '*'        


app:
  message:
    
    usernotfound : User Details Not Found with
    mailsubject  : HIS Register Password
    bodycontent  : "<h3>Use this First time Login Password </h3>"
    existingusermsg : User is already Existing. Please Login
    usernotfoundcode : HIS0001
    userexsitingcode : HIS0002
    registersuccessmsg : User Register Succesfully.
    registerfailedmsg  : Failed to Save User Details.
    loginsuccessmsg : Login Successfully.
    loginfailedmsg   : Login Failed.
    usercredentialsfailedmsg : Please Use Validate Credentials.
    usercredentialscode      : HIS0003
    
    
    successMessage: "Login successful!"
    failureMessage: "Invalid credentials. Please try again."
    mailSubject   : "HIS-Forget-Password"
    dashboardGreet: "Welcome to Dashboard "
    unAuth        : "Unauthorized access"
    interanlServerError : "Internal Server Error"
    registerSuccess : "Citizen is Register Successfully."
    exstingCitizen  : "Citizen is Already with Register "
    mailSent       : "Mail Sent Successfully to "
    logoutMessage  : "Logout Successfully"
    invalidEmailExcpt : "Login With Register Email"  
    updatePwdMessage  : "Password is Updated"
    invalidEmail : "Use Validate Email Forget"
    confirmPwd  : "Please Enter Same Password"
